version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: recipes_user
      POSTGRES_PASSWORD: recipes_password
      POSTGRES_DB: recipes_db
    ports:
      - '5432:5432'
    volumes:
      - recipes_data:/var/lib/postgres/data

  recipes_app:
    build:
      context: ./recipes
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: on-failure:10

volumes:
  recipes_data: