# Generated by Django 5.0.1 on 2024-02-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeproduct',
            unique_together={('recipe', 'product')},
        ),
    ]
